DROP TABLE IF EXISTS recipe;

CREATE TABLE recipe (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	recipename TEXT NOT NULL,
	filename TEXT NOT NULL,
	ingredients TEXT NOT NULL,
	directions TEXT NOT NULL
);
